### ISSUE TITLE
Jenkins plugins are not installed

### ISSUE THREAD

**Issue by NavidZisky** [rancher/community-catalog#82]
Due to not automatically resolved dependencies, plugins which are chosen by default when spinning jenkins from rancher catalog, are not installed:

LOGS:

java.io.IOException: Dependency git (2.0.3) doesn't exist
29/03/2016 20:10:09	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
29/03/2016 20:10:09	at hudson.PluginManager$2$1$1.run(PluginManager.java:383)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
29/03/2016 20:10:09	at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29/03/2016 20:10:09	at java.lang.Thread.run(Thread.java:745)
29/03/2016 20:10:09
29/03/2016 20:10:09Mar 29, 2016 6:10:09 PM jenkins.InitReactorRunner$1 onTaskFailed
29/03/2016 20:10:09SEVERE: Failed Loading plugin plain-credentials
29/03/2016 20:10:09java.io.IOException: Dependency credentials (1.21) doesn't exist
29/03/2016 20:10:09	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
29/03/2016 20:10:09	at hudson.PluginManager$2$1$1.run(PluginManager.java:383)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
29/03/2016 20:10:09	at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29/03/2016 20:10:09	at java.lang.Thread.run(Thread.java:745)
29/03/2016 20:10:09
29/03/2016 20:10:09Mar 29, 2016 6:10:09 PM jenkins.InitReactorRunner$1 onTaskFailed
29/03/2016 20:10:09SEVERE: Failed Loading plugin github
29/03/2016 20:10:09java.io.IOException: Dependency credentials (1.22), plain-credentials (1.1), git (2.4.0), token-macro (1.11) doesn't exist
29/03/2016 20:10:09	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
29/03/2016 20:10:09	at hudson.PluginManager$2$1$1.run(PluginManager.java:383)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
29/03/2016 20:10:09	at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29/03/2016 20:10:09	at java.lang.Thread.run(Thread.java:745)
29/03/2016 20:10:09
29/03/2016 20:10:09Mar 29, 2016 6:10:09 PM jenkins.InitReactorRunner$1 onTaskFailed
29/03/2016 20:10:09SEVERE: Failed Loading plugin ssh-slaves
29/03/2016 20:10:09java.io.IOException: Dependency ssh-credentials (1.6.1), credentials (1.9.4) doesn't exist
29/03/2016 20:10:09	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
29/03/2016 20:10:09	at hudson.PluginManager$2$1$1.run(PluginManager.java:383)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
29/03/2016 20:10:09	at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
29/03/2016 20:10:09	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29/03/2016 20:10:09	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29/03/2016 20:10:09	at java.lang.Thread.run(Thread.java:745)

**Comment by cloudnautique** [comment]
Yes, this is true. If you add a plugin, you have to add all of its dependencies as well. We are leveraging the builtin script within the container to accomplish this. 

Do you know of a good package/plugin manager outside of Jenkins UI that could help resolve this? Not sure what we can do here, and open to suggestions =D

**Comment by NavidZisky** [comment]
I'm just testing one solution. Of course will let You know if will work :) Cheers

**Comment by NavidZisky** [comment]
Ok fixed.

- [ ] 1.  Edit /usr/share/jenkins/rancher/jenkins.sh

```
#!/bin/bash

/usr/local/bin/plugins.sh /usr/share/jenkins/rancher/plugins.txt
exec /bin/tini -- /usr/local/bin/jenkins.sh
```

- [ ] 2.  Edit /usr/local/bin/plugins.sh

[https://gist.github.com/NavidZisky/cbd43a2b1946528b729f4a0202cf7a4b](url)


- [ ] 3. Enjoy

 :)

Big thanks to @rpetti for code which downloads also dependencies ;)

Tested with latest (1.0) rancher.

**Comment by NavidZisky** [comment]
@cloudnautique could You take a look?

**Comment by cloudnautique** [comment]
@NavidZisky, I get a 404 on the Gist. Is it private?

If you have a fix for the jenkins plugin.sh script, it would be awesome to get it in upstream. In general, we do not want to take on managing the Jenkins image, and everyone could benefit from this fix.

**Comment by NavidZisky** [comment]
@cloudnautique ahhh sorry, yes it was private - I changed it to public. And I couldn't find a place where I can commit it that's why I give it to You like this ;)

**Comment by NavidZisky** [comment]
@cloudnautique  Hi again :) I understand that You probably has a lot of work, but my solution is tested and working, so if You could just make those changes that we could start using rancher in our env (since we use jenkins a lot) ;) and probably not only us are waiting for this fix :) Cheers

**Comment by Dreampie** [comment]
```

2016年5月30日 GMT+8 下午1:28:56Downloading plain-credentials:latest
2016年5月30日 GMT+8 下午1:28:59Downloading scm-api:latest
2016年5月30日 GMT+8 下午1:29:01Downloading ssh-credentials:latest
2016年5月30日 GMT+8 下午1:29:04Downloading ssh-slaves:latest
2016年5月30日 GMT+8 下午1:29:07Downloading swarm:latest
2016年5月30日 GMT+8 下午1:29:10Downloading gradle:latest
2016年5月30日 GMT+8 下午1:29:12Downloading maven:latest
2016年5月30日 GMT+8 下午1:29:14curl: (22) The requested URL returned error: 404 Not Found
2016年5月30日 GMT+8 下午1:29:14Running from: /usr/share/jenkins/jenkins.war
2016年5月30日 GMT+8 下午1:29:14webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2016年5月30日 GMT+8 下午1:29:14May 30, 2016 5:29:14 AM winstone.Logger logInternal
2016年5月30日 GMT+8 下午1:29:14INFO: Beginning extraction from war file
2016年5月30日 GMT+8 下午1:29:15May 30, 2016 5:29:15 AM org.eclipse.jetty.util.log.JavaUtilLog info
2016年5月30日 GMT+8 下午1:29:15INFO: jetty-winstone-2.9
2016年5月30日 GMT+8 下午1:29:16May 30, 2016 5:29:16 AM org.eclipse.jetty.util.log.JavaUtilLog info
2016年5月30日 GMT+8 下午1:29:16INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
2016年5月30日 GMT+8 下午1:29:16Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2016年5月30日 GMT+8 下午1:29:17May 30, 2016 5:29:17 AM org.eclipse.jetty.util.log.JavaUtilLog info
2016年5月30日 GMT+8 下午1:29:17INFO: Started SelectChannelConnector@0.0.0.0:8080
2016年5月30日 GMT+8 下午1:29:17May 30, 2016 5:29:17 AM winstone.Logger logInternal
2016年5月30日 GMT+8 下午1:29:17INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
2016年5月30日 GMT+8 下午1:29:17May 30, 2016 5:29:17 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:17INFO: Started initialization
2016年5月30日 GMT+8 下午1:29:22May 30, 2016 5:29:22 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:22INFO: Listed all plugins
2016年5月30日 GMT+8 下午1:29:22May 30, 2016 5:29:22 AM jenkins.InitReactorRunner$1 onTaskFailed
2016年5月30日 GMT+8 下午1:29:22SEVERE: Failed Loading plugin github
2016年5月30日 GMT+8 下午1:29:22java.io.IOException: Dependency token-macro (1.11) doesn't exist
2016年5月30日 GMT+8 下午1:29:22	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
2016年5月30日 GMT+8 下午1:29:22	at hudson.PluginManager$2$1$1.run(PluginManager.java:383)
2016年5月30日 GMT+8 下午1:29:22	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
2016年5月30日 GMT+8 下午1:29:22	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
2016年5月30日 GMT+8 下午1:29:22	at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
2016年5月30日 GMT+8 下午1:29:22	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
2016年5月30日 GMT+8 下午1:29:22	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
2016年5月30日 GMT+8 下午1:29:22	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016年5月30日 GMT+8 下午1:29:22	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016年5月30日 GMT+8 下午1:29:22	at java.lang.Thread.run(Thread.java:745)
2016年5月30日 GMT+8 下午1:29:22
2016年5月30日 GMT+8 下午1:29:22May 30, 2016 5:29:22 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:22INFO: Prepared all plugins
2016年5月30日 GMT+8 下午1:29:22May 30, 2016 5:29:22 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:22INFO: Started all plugins
2016年5月30日 GMT+8 下午1:29:22May 30, 2016 5:29:22 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:22INFO: Augmented all extensions
2016年5月30日 GMT+8 下午1:29:24May 30, 2016 5:29:24 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:24INFO: Loaded all jobs
2016年5月30日 GMT+8 下午1:29:24May 30, 2016 5:29:24 AM jenkins.util.groovy.GroovyHookScript execute
2016年5月30日 GMT+8 下午1:29:24INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM hudson.model.AsyncPeriodicWork$1 run
2016年5月30日 GMT+8 下午1:29:25INFO: Started Download metadata
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM org.jenkinsci.main.modules.sshd.SSHD start
2016年5月30日 GMT+8 下午1:29:25INFO: Started SSHD at port 51024
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Completed initialization
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Started initialization
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Listed all plugins
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Prepared all plugins
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Started all plugins
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Augmented all extensions
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Loaded all jobs
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午1:29:25INFO: Completed initialization
2016年5月30日 GMT+8 下午1:29:25May 30, 2016 5:29:25 AM hudson.WebAppMain$3 run
2016年5月30日 GMT+8 下午1:29:25INFO: Jenkins is fully up and running
2016年5月30日 GMT+8 下午1:29:34--> setting agent port for jnlp
2016年5月30日 GMT+8 下午1:29:34--> setting agent port for jnlp... done
```
